Magit Boost is an Emacs package designed to accelerate Magit's performance when used over high-latency networks, such as corporate VPNs. Magit's default implementation assumes fast shell command execution and file access, an assumption that often doesn't hold true in these environments. This module optimizes Magit by advising specific Git and Tramp functions to introduce several improvements:
1. Reducing the number of =git= commands by utilizing cached information or performing basic path computations. 
2. Batching commands related to file attributes within the Git tree. 
3. Implementing optimized versions of synchronous =git= command execution.

* Installation

Add =magit-boost.el= to your Emacs load path and require it:

#+begin_src emacs-lisp
(require 'magit-boost)
#+end_SRC

* Usage

Enable =magit-boost-mode= globally to accelerate Magit operations:

#+begin_src emacs-lisp
(magit-boost-mode 1)
#+end_src

When enabled, Magit Boost intercepts Magit Git commands and routes them through a persistent Bash process.

*Note*: It automatically falls back to standard Magit behavior for non-remote (TRAMP) buffers.

